# Site settings
title: Fizjoterapia Gdańsk
description: "Gabinet fizjoterapii, Gdańsk, trójmiasto. Paweł Jendrzejewski"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: img/logo.jpg

# Hero
hero: 
    hero_img: hero2.png
    hero_title: Gabinet fizjoterapii
    hero_description: Paweł Jendrzejewski
# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: +48 792 512 907
    email: pawel.jendrzejewski@gmail.com
    address: ul. Miszewskiego 12/13 <br> Gdańsk, 80-239 <br> (budynek Zakładu Doskonalenia Zawodowego) <br> ul. Juliusza Słowackiego 4 <br> Gdańsk, 80-257 <br> (teren klubu Fitness Spójnia)
# Opening hours
monday_friday: 8:00 – 22:00
saturday: 8:00 – 17:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Von schroeders 273, Viña del mar, Chile
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
